[versions]

papermc = "1.21.1-R0.1-SNAPSHOT"
lombok = "1.18.32"

[libraries]

papermc = { group = "io.papermc.paper", name = "paper-api", version.ref = "papermc" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }